import { COLORS } from "@/constants/Colors";
import { scale, scaleText } from "@/constants/Layout";
const { StyleSheet } = require("react-native");

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  map: { flex: 1 },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  loadingText: {
    fontSize: scaleText(18),
    color: COLORS.text,
    marginTop: scale(16),
  },
  errorContainer: {
    position: "absolute",
    top: scale(120),
    left: scale(20),
    right: scale(20),
    backgroundColor: COLORS.error,
    borderRadius: scale(8),
    padding: scale(12),
    zIndex: 1000,
  },
  errorText: {
    fontSize: scaleText(14),
    color: COLORS.white,
    textAlign: "center",
  },
  buttonContainer: {
    position: "absolute",
    top: scale(60),
    left: scale(25),
    right: scale(25),
    zIndex: 1000,
  },
  menuButton: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  backButton: {
    width: scale(80),
    height: scale(40),
    borderRadius: scale(20),
    backgroundColor: COLORS.secondaryText,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  backButtonText: {
    fontSize: scaleText(16),
    color: COLORS.white,
    fontWeight: "700",
  },
  cancelButton: {
    width: scale(100),
    height: scale(40),
    borderRadius: scale(20),
    backgroundColor: "#FF4500",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  cancelButtonText: {
    fontSize: scaleText(16),
    color: COLORS.white,
    fontWeight: "700",
  },
  bottomSheet: { zIndex: 1900 },
  bottomSheetBackground: {
    backgroundColor: COLORS.background,
    borderTopLeftRadius: scale(16),
    borderTopRightRadius: scale(16),
  },
  bottomSheetHandle: {
    backgroundColor: COLORS.secondaryText,
    width: scale(40),
    height: scale(4),
  },
  bottomSheetContent: { flex: 1, padding: scale(16) },
  whereToButton: {
    backgroundColor: COLORS.white,
    borderRadius: scale(12),
    padding: scale(16),
    marginBottom: scale(16),
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  whereToButtonText: {
    fontSize: scaleText(18),
    color: COLORS.text,
    fontWeight: "700",
  },
  sectionTitle: {
    fontSize: scaleText(22),
    color: COLORS.text,
    marginBottom: scale(12),
    fontWeight: "700",
  },
  sectionSubTitle: {
    fontSize: scaleText(16),
    color: COLORS.secondaryText,
    marginBottom: scale(12),
    fontWeight: "500",
  },
  recentDestinationsList: { flex: 1 },
  recentDestinationCard: {
    backgroundColor: COLORS.white,
    borderRadius: scale(12),
    padding: scale(12),
    marginBottom: scale(12),
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  recentDestinationContent: { flexDirection: "row", alignItems: "center" },
  recentDestinationIcon: {
    width: scale(24),
    height: scale(24),
    marginRight: scale(12),
  },
  recentDestinationText: { fontSize: scaleText(16), color: COLORS.text },
  recentDestinationSubText: {
    fontSize: scaleText(12),
    color: COLORS.secondaryText,
  },
  confirmCard: {
    backgroundColor: COLORS.white,
    borderRadius: scale(12),
    padding: scale(16),
    marginBottom: scale(16),
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  locationCard: {
    backgroundColor: COLORS.white,
    borderRadius: scale(12),
    padding: scale(16),
    marginBottom: scale(16),
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: scale(8),
  },
  locationIcon: { width: scale(24), height: scale(24), marginRight: scale(12) },
  locationText: { fontSize: scaleText(14), color: COLORS.text, flex: 1 },
  locationDivider: {
    height: 1,
    backgroundColor: COLORS.secondaryText,
    opacity: 0.2,
    marginVertical: scale(8),
  },
  rideOptionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: scale(8),
  },
  rideOptionIcon: {
    width: scale(40),
    height: scale(40),
    marginRight: scale(12),
  },
  rideOptionTitle: {
    fontSize: scaleText(16),
    color: COLORS.text,
    fontWeight: "700",
  },
  rideOptionDescription: {
    fontSize: scaleText(14),
    color: COLORS.secondaryText,
    marginVertical: scale(4),
  },
  rideOptionDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: scale(8),
  },
  rideOptionPrice: {
    fontSize: scaleText(14),
    color: COLORS.text,
    fontWeight: "700",
  },
  rideOptionDuration: { fontSize: scaleText(14), color: COLORS.secondaryText },
  bookButton: {
    backgroundColor: COLORS.primary,
    borderRadius: scale(12),
    padding: scale(16),
    alignItems: "center",
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  bookButtonDisabled: { backgroundColor: COLORS.secondaryText },
  bookButtonText: {
    fontSize: scaleText(16),
    color: COLORS.white,
    fontWeight: "700",
  },
  contactButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  contactButton: {
    backgroundColor: COLORS.error,
    borderRadius: scale(12),
    padding: scale(12),
    alignItems: "center",
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
  },
  contactButtonText: {
    fontSize: scaleText(16),
    color: COLORS.white,
    fontWeight: "700",
  },
  searchAnimation: { alignItems: "center", marginTop: scale(16) },
  searchText: {
    fontSize: scaleText(14),
    color: COLORS.secondaryText,
    marginTop: scale(12),
  },
  markerIcon: { width: scale(32), height: scale(32) },
  tricycleMarker: { width: scale(40), height: scale(40) },
  driverPicture: {
    width: scale(48),
    height: scale(48),
    borderRadius: scale(24),
    marginRight: scale(12),
  },
  driverInfoContainer: { flex: 1 },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: scale(4),
  },
  starIcon: { width: scale(16), height: scale(16), marginRight: scale(4) },
  tripCard: {
    backgroundColor: COLORS.white,
    borderRadius: scale(12),
    padding: scale(16),
    marginBottom: scale(16),
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  driverHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: scale(12),
  },
  tripInfoContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: scale(12),
    borderTopWidth: 1,
    borderTopColor: COLORS.secondaryText,
  },
  tripInfoItem: { flex: 1, alignItems: "center" },
  tripInfoLabel: {
    fontSize: scaleText(12),
    color: COLORS.secondaryText,
    marginBottom: scale(4),
  },
  tripInfoValue: { fontSize: scaleText(16), color: COLORS.text },
  tripInfoDivider: {
    width: 1,
    height: scale(30),
    backgroundColor: COLORS.secondaryText,
    opacity: 0.2,
  },
  chatContainer: {
    flex: 1,
    padding: scale(16),
  },
  chatList: {
    flexGrow: 1,
    marginBottom: scale(10),
  },
  chatListContent: {
    paddingBottom: scale(80), // Space for input
    flexGrow: 1,
    justifyContent: "flex-end",
  },
  messageBubble: {
    maxWidth: "80%",
    marginVertical: scale(4),
    padding: scale(12),
    borderRadius: scale(12),
    marginHorizontal: scale(8),
  },
  sentMessage: {
    backgroundColor: COLORS.primary,
    alignSelf: "flex-end",
  },
  receivedMessage: {
    backgroundColor: COLORS.lightGray,
    alignSelf: "flex-start",
  },
  messageSender: {
    fontSize: scale(12),
    color: COLORS.white,
    marginBottom: scale(4),
    opacity: 0.8,
  },
  messageText: {
    fontSize: scale(14),
    color: COLORS.white,
  },
  messageTime: {
    fontSize: scale(10),
    color: COLORS.white,
    opacity: 0.6,
    marginTop: scale(4),
    textAlign: "right",
  },
  chatInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: scale(8),
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.lightGray,
  },
  chatInput: {
    flex: 1,
    backgroundColor: COLORS.lightGray,
    borderRadius: scale(20),
    padding: scale(10),
    fontSize: scale(14),
    maxHeight: scale(100),
    marginRight: scale(8),
  },
  sendButton: {
    backgroundColor: COLORS.primary,
    borderRadius: scale(20),
    padding: scale(10),
    justifyContent: "center",
    alignItems: "center",
  },
  sendButtonDisabled: {
    backgroundColor: COLORS.gray,
  },
  chatLoadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});
